Feature/dgi 89
IT-Minds/client_dansk-gartneri_indberetning pull request #258
Opened 2022-01-06 10:44 UTC by MichaelJeppesen

Makes all the value numbers in the csv-file for statements negative

2022-01-07 14:06 UTC, objmj-itminds requested changes

2022-01-07 14:06 UTC, objmj-itminds commented on backend/Application/Statements/Queries/GetStatementsCSV/GetStatementsCSVQuery.cs
> +
I would rather we actually do these attributes individually with a `.Select`

2022-01-07 14:06 UTC, objmj-itminds commented on backend/Web/Controllers/StatementController.cs
> +      _ = await Mediator.Send(new UnassignAccountantCommand
Please remove the assignment.

2022-01-10 09:34 UTC, CSCITM commented on backend/Application/Statements/Queries/GetStatementsCSV/GetStatementsCSVQuery.cs
> +        System.Collections.Generic.List<StatementCSVDto> statements = await _context.Statements
Add the correct using instead of this.

2022-01-13 10:18 UTC, objmj-itminds approved these changes

2022-01-13 10:18 UTC, merged