Feature/dgi 92
IT-Minds/client_dansk-gartneri_indberetning pull request #259
Opened 2022-01-06 10:48 UTC by MichaelJeppesen

- Added a hook to get methods that format numbers in different ways
 - Added methods to format numbers with thousand separators, one which includes decimals, and one which does not
 - Added a method to convert a formatted string-number back into a number (as when using "." as thousand-separator it is seen as a decimal and converts to the wrong number with parseInt)
- formatted the InputDKK with thousand-separator without decimal
- formatted the TaxTotal with thousand-separator with decimal

2022-01-10 05:28 UTC, objmj-itminds commented on frontend/src/components/Statement/TaxTotal.tsx
> +    return formatNumberThousandSepDecimal(((form[name] as number) * tax) / 1000);
Lets use 

``` 
<NumberFormat
              decimalSeparator=","
              thousandSeparator="."
              prefix={"$"}
            />```

2022-01-19 08:04 UTC, objmj-itminds requested changes
I still feel like we can drop the custom hook completely.

2022-01-19 09:48 UTC, MichaelJeppesen commented
> 

I cant seem to format the NumberFormat element as i want
cannot set bgColor, rounded corners, it always just ends up being a white box, with white text

![Screenshot 2022-01-19 104623](https://user-images.githubusercontent.com/90178394/150105718-5adc4453-f79b-4798-8b85-9249214b0610.png)
i can only see the text because i have marked it

it should be possible to add a renderText property which should be how it is rendered, but when i set bgColors, roundLeft etc. on that element, nothing changes

2022-01-21 10:54 UTC, objmj-itminds commented
I'll take over this branch.

2022-01-21 10:54 UTC, closed without merging