Feature/dgi 103
IT-Minds/client_dansk-gartneri_indberetning pull request #263
Opened 2022-01-12 11:43 UTC by MichaelJeppesen

Added a reminder email to send to client who have not signed off yet
Added buttons to send reminder/invite to all relevant clients, which opens a popup to choose exactly who will get the mail

2022-01-12 12:54 UTC, CSCITM requested changes
![image](https://user-images.githubusercontent.com/37330630/149144219-d8f9f1b1-5f09-4603-a5ce-d5117595dc8c.png)

2022-01-14 10:04 UTC, objmj-itminds requested changes

2022-01-14 12:26 UTC, objmj-itminds approved these changes

2022-01-21 08:38 UTC, CSCITM approved these changes

2022-01-21 08:57 UTC, merged