Feature/dgi 105
IT-Minds/client_dansk-gartneri_indberetning pull request #266
Opened 2022-01-17 11:02 UTC by MichaelJeppesen

Added functionality to attach a file to a statement and download it again

2022-01-17 11:21 UTC, CSCITM requested changes
Generally we wont review before all checks are successful, please keep an eye on failing checks.
![image](https://user-images.githubusercontent.com/37330630/149760786-f618e316-538a-46ce-9f73-645a9b122fe3.png)

2022-01-18 11:46 UTC, objmj-itminds requested changes

2022-01-18 11:46 UTC, objmj-itminds commented on frontend/src/components/Accounts/AccountList/AccountListItemButtons/EditOptions/DownloadStatementFileBtn.tsx
> +  }, []);
I am pretty sure we already have a util for this. If not create one.

2022-01-18 11:46 UTC, objmj-itminds commented on frontend/src/components/Accounts/AccountList/AccountListItemButtons/EditOptions/DownloadStatementFileBtn.tsx
> +      )}
The logic for this should probably be outside this component. Instead, consider throwing an error before the return if there isn't a `statementFileName`.

2022-01-18 11:46 UTC, objmj-itminds commented on frontend/src/components/Accounts/AccountList/AccountListItemButtons/EditOptions/UploadStatementFileModal.tsx
> +    console.log(file.name);
Remember not to use `console.log` instead, try the other functions for more precise logging. Or simply remove if not needed during production runtime.

2022-01-18 14:45 UTC, CSCITM requested changes

2022-01-18 14:45 UTC, CSCITM commented on backend/Web/Controllers/StatementController.cs
> +    public async Task<ActionResult<StatementFileDto>> GetStatementFile([FromRoute] int id)
Look into file results
https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.fileresult?view=aspnetcore-6.0

2022-01-20 13:02 UTC, CSCITM requested changes

2022-01-20 13:02 UTC, CSCITM commented on backend/Application/Statements/Queries/GetStatementFile/GetStatementFileQuery.cs
> +          data = new byte[fileStream.Length];
Have you considered using FileStreamResult in the controller to be able to pass the stream directly?

2022-01-21 12:20 UTC, CSCITM commented
![image](https://user-images.githubusercontent.com/37330630/150526023-9c7b8bec-8b6f-4e6e-8cf4-60a6bdb87152.png)
Please check for merge conflicts and failed checks, it's happens in too many of your PR's.

2022-01-24 10:33 UTC, merged