Feature/DGI-45: Command to update user
IT-Minds/client_dansk-gartneri_indberetning pull request #58
Opened 2021-03-16 12:46 UTC by ntw-ITM

Issue DGI-45 was originally about making a command to update specifically an accountant, but as I see it, it might as well be more general for updating a user. I assume that the account or role of the user cannot be updated, and that if an accountant should be removed from an account, it should be deactivated.

One could argue, that if the user to update is a 'client' (not an accountant), and the user is updated to a deactivated state, the account should also be deactivated, as well as any accountant on that account.

2021-03-21 12:53 UTC, objmj-itminds commented on backend/Application/Users/Commands/UpdateUserCommand/UpdateUserCommand.cs
> +        userEntity.DeactivationTime = request.User.DeactivationTime ?? userEntity.DeactivationTime;
I'm not too fond of the deactivation time being part of the update here. I would suggest making another command that takes an ID and then sets the deactivation time from the backend side. This way, we avoid issues with timezones and MIM issues,

2021-03-21 16:32 UTC, ntw-ITM commented on backend/Application/Users/Commands/UpdateUserCommand/UpdateUserCommand.cs
> +        userEntity.DeactivationTime = request.User.DeactivationTime ?? userEntity.DeactivationTime;
That makes sense. I now created another command just to deactivate a user. I also updated the UserController with endpoints to these commands.

2021-03-22 08:15 UTC, objmj-itminds requested changes

2021-03-22 08:15 UTC, objmj-itminds commented on backend/Application.UnitTests/Application.UnitTests.csproj
> +
I don't know why you are generating these files or adding them to the commit. But please, don't.

2021-03-22 08:15 UTC, objmj-itminds commented on backend/Web/Controllers/UserController.cs
> +    [HttpPut("deactivate/{id}")]
"{id}/deactivate"

2021-03-22 08:15 UTC, objmj-itminds commented on backend/Web/Controllers/UserController.cs
> +    [HttpPut("changePassword/{id}")]
"{id}/changePassword"

2021-03-22 09:22 UTC, ntw-ITM commented on backend/Application.UnitTests/Application.UnitTests.csproj
> +
Visual studio generates these changes whenever I add a new folder. I unstage them all the time, and I usually check all file changes before a PR, but I guess I missed this one.

2021-03-22 09:27 UTC, ntw-ITM commented
Added requested changes.

2021-03-22 11:02 UTC, objmj-itminds approved these changes

2021-03-22 11:03 UTC, merged