Feature/DGI-37: UI Form to change password
IT-Minds/client_dansk-gartneri_indberetning pull request #60
Opened 2021-03-16 14:07 UTC by ntw-ITM

I chose to create my own custom hook, usePasswordvalidation, because the logic may be used other places as well.

2021-03-21 13:46 UTC, objmj-itminds requested changes

2021-03-21 13:46 UTC, objmj-itminds commented on frontend/src/hooks/usePasswordValidation.ts
> +export const usePasswordValidation = () => {
While I am a fan of this hook and the approach, it can also be simplified.

The rules only need to apply to the first password as the second password only needs to copy the first.
If the first password follows all the rules and the second copies the first, it also follows the rules.

Then after asserting only having to check the first password, this entire hook can be rewritten to only check rules for ONE password. A simple boolean, an array of errors, and the check function is all it needs to return. Remember you can have parameters in a hook.

2021-03-21 13:46 UTC, objmj-itminds commented on frontend/src/components/User/ChangePassword/ChangePasswordForm.tsx
> +        1, //TODO: Change to id of active user.
Do you have a PR this depends on or issue?

2021-03-21 13:46 UTC, objmj-itminds commented on frontend/src/components/User/ChangePassword/ChangePasswordForm.tsx
> +      onSubmit(e);
Try / catch this and give some toasts on the result.

2021-03-21 13:46 UTC, objmj-itminds commented on frontend/src/components/User/ChangePassword/ChangePasswordForm.tsx
> +  onSubmit?: (e: React.FormEvent) => void;
In most cases, you wouldn't want the event but the context of this component's result. So start with a boolean if the update went well.

2021-03-21 16:45 UTC, ntw-ITM commented on frontend/src/hooks/usePasswordValidation.ts
> +export const usePasswordValidation = () => {
Glad you're a fan!
Actually the code functions just as you suggest: It only applies the rules to the first password and then checks if the second password is equal to the first. But I see your point, that the hook doesn't need to consider the second password, so I'll simplify that part.

2021-03-22 08:04 UTC, ntw-ITM commented on frontend/src/hooks/usePasswordValidation.ts
> +export const usePasswordValidation = () => {
Now I changed the hook, so that it no longer keeps state of passwords, but only exports a method to check passwords and return a result. I also updated the changePasswordForm according to the changes.

2021-03-22 08:05 UTC, ntw-ITM commented on frontend/src/components/User/ChangePassword/ChangePasswordForm.tsx
> +        1, //TODO: Change to id of active user.
This is now implemented, as I had to apply recent changes to "Main" anyway.

2021-03-22 08:05 UTC, ntw-ITM commented on frontend/src/components/User/ChangePassword/ChangePasswordForm.tsx
> +      onSubmit(e);
Done

2021-03-22 08:06 UTC, ntw-ITM commented on frontend/src/components/User/ChangePassword/ChangePasswordForm.tsx
> +  onSubmit?: (e: React.FormEvent) => void;
Now takes a boolean instead.

2021-03-22 08:19 UTC, objmj-itminds approved these changes

2021-03-22 08:19 UTC, merged