Feature/DGI-41: Generate and validate SSO Token
IT-Minds/client_dansk-gartneri_indberetning pull request #62
Opened 2021-03-19 09:37 UTC by ntw-ITM

I'm not sure how long the tokens should be valid for. For now, I've set it to 7 days, but I guess that may be too long.

2021-03-21 12:14 UTC, objmj-itminds requested changes

2021-03-21 12:14 UTC, objmj-itminds commented on backend/Web/Services/TokenService.cs
> +      _context.SaveChanges();
Instead of having this service mutating and writing to db instead, return a tuple of the id and written token.

2021-03-21 12:14 UTC, objmj-itminds commented on backend/Web/Services/TokenService.cs
> +      var user = await _context.Users.FindAsync(((JwtSecurityToken)validatedToken).Claims.First(claim => claim.Type == ClaimTypes.NameIdentifier).Value);
We don't want any DB reads in this service. Simply return the user identifier.

2021-03-21 12:14 UTC, objmj-itminds commented on frontend/src/services/backend/nswagts.ts
> +    ssoTokenId?: string | null;
I don't like that this ID is here, and I can't find it in any committed DTO. I don't think the frontend needs this ID.

2021-03-22 10:44 UTC, ntw-ITM commented
Added requested changes to TokenService. Also Added Newtonsoft.Json to Domain project to use JsonIgnore on ssoTokenId property.

2021-03-22 13:13 UTC, objmj-itminds approved these changes

2021-03-22 13:13 UTC, objmj-itminds commented on backend/Domain/Entities/AdminUser.cs
> +    [JsonIgnore]
I didn't mean to pull logic into your domain. 

The issue is you are using IUser outside the domain which can cause a reference to the attribute.

2021-03-22 13:14 UTC, objmj-itminds requested changes
Mistakenly approved.

2021-03-22 19:01 UTC, ntw-ITM commented
I have now removed the JsonIgnores again and uninstalled Newtonsoft.Json from Domain project. I have removed the SSOTokenId property from IUser, but the issue with it being generated in nswagts.ts has not been resolved.

2021-03-23 08:19 UTC, objmj-itminds approved these changes

2021-03-23 08:19 UTC, merged