Feature/DGI-50: Add RazorEmail project and welcome email
IT-Minds/client_dansk-gartneri_indberetning pull request #63
Opened 2021-03-19 10:03 UTC by ntw-ITM

The large changes to the .sln file were probably made by Visual Studio when I added the new project. I don't think It's related to line endings.

2021-03-21 13:54 UTC, objmj-itminds requested changes

2021-03-21 13:54 UTC, objmj-itminds commented on backend/RazorEmails/Views/Shared/EmailButton.cshtml
> +  <!--[if mso]></center></v:textbox></v:roundrect></td></tr></table><![endif]-->
Please line end some more.

2021-03-21 13:54 UTC, objmj-itminds commented on backend/RazorEmails/Views/Shared/EmailLayout.cshtml
> +<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional //EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
There is a lot of mixes between having a stylesheet and then inline style. Please pick a lane and stick to it.

2021-03-21 13:54 UTC, objmj-itminds commented on backend/RazorEmails/Views/Shared/EmailLayout.cshtml
> +<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional //EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
Make sure you are also following this
https://templates.mailchimp.com/getting-started/html-email-basics/

2021-03-22 12:45 UTC, ntw-ITM commented
Now I made a totally new email layout, using both the link you shared and this guide: https://webdesign.tutsplus.com/articles/creating-a-simple-responsive-html-email--webdesign-12978
It's a whole lot simpler than the generated one. It still uses a mix of both stylesheet and inline styling, but I hope it's not too much of an issue. I've made a small styling of a "mailSection" class in the stylesheet to be used by sections that are put into the body.

2021-03-22 14:35 UTC, objmj-itminds approved these changes

2021-03-22 14:35 UTC, merged