Feature/DGI-46: Modal to edit accountant for account
IT-Minds/client_dansk-gartneri_indberetning pull request #68
Opened 2021-03-24 09:22 UTC by ntw-ITM

I have made a lot of changes in this branch that wasn't originally part of this issue, but I decided that they were necessary to make this feature work properly. This is why so many files have changed.

Some changes:
- I decided I had to remove Email as an index from the fluent configuration of Users, because if eg. you add an accountant with an email that has been added before, but has since been deactivated, it won't allow it. Because of this change, I made a new migration.
- There were some errors in CreateAccountantCommand in the way it checked if the provided email was already in use. I think this is also an error in some other commands, which I will check and maybe fix in another PR.
- As we talked about yesterday, it makes sense to use entity extensions. This has been implemented here as well, because it was needed for the feature.
- Because I'm starting to have deeply nested components in the table view of accounts that need to eg. fetch data, I have made an AccountsContext that is provided in components/accounts.tsx.
- I have made a few modifications to the table view of accounts to better display the accountant and option to edit it.

2021-03-24 09:57 UTC, ntw-ITM commented
@objmj-itminds  and @CSCITM , I know that the backend build check fails. This is because GetAccountsQueryTest suddenly fails. I'm fairly sure it has something to do with the entity extension of Account and the mappings on AccountDto. But I don't understand what's wrong. Can you spot it?

2021-03-25 09:48 UTC, ntw-ITM commented
Request for review retracted, as I've chosen to make more changes.

2021-03-25 10:31 UTC, objmj-itminds requested changes
Don't remove email but do as we discussed earlier regarding activating old users.

2021-03-29 08:03 UTC, objmj-itminds commented on backend/Domain/EntityExtensions/AccountExtensions.cs
> +      }
If you use `FirstOrDefault` there shouldn't be a need to try/catch.

2021-03-29 08:10 UTC, objmj-itminds commented on frontend/src/components/Accounts/ChangeAccountant/CurrentAccountant.tsx
> +    async (e: React.MouseEvent) => {
In most cases, we never want the actual 'event'. If a parameter is always used in one singular way, then move that logic out of the callback.

2021-03-29 08:11 UTC, objmj-itminds approved these changes

2021-03-29 09:15 UTC, merged